### ISSUE TITLE
开发讨论

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/ChineseLinter.vim#1]
这个插件主要基于 [中文文案排版指北（简体中文版）](https://github.com/mzlogin/chinese-copywriting-guidelines) 中的一些定义实现的，目前还需要加入以下检查：

1。 重复使用标点符号

**Comment by amitbha** [comment]
2. 连续存在多个空行（> 2个）
插件为什么不支持自动修复？

**Comment by wsdjeg** [comment]
自动修复以后有机会在加，逻辑和语法检查完全不一样了。

**Comment by xylinkun** [comment]
Please close the issue by this [PR11](https://github.com/wsdjeg/ChineseLinter.vim/pull/11)
