### ISSUE TITLE
请求删除doc中的中文，替换成英文。

### ISSUE THREAD

**Issue by ssfdust** [wsdjeg/ChineseLinter.vim#15]
如果在SpaceVim中启用chinese Layer，调用
dein#recache_runtimepath 会报Mix encode的错误
如果单独禁用掉ChineseLinter.vim则不会
排查后发现是ChineseLinter.vim的doc中含有中文，能否替换成英文
在Archlinux中可以复现

**Comment by wsdjeg** [comment]
帮助文档时自动生成的，需要修改 vim 文件
