### ISSUE TITLE
能否加入自动 fix 功能？

### ISSUE THREAD

**Issue by FuDesign2008** [wsdjeg/ChineseLinter.vim#19]
个人感觉 ChineseLinter.vim 比 [pangu.vim](https://github.com/hotoo/pangu.vim) 优秀的地方在于，定义了错误代码 —— 类似编程语言的 linter，比较严谨。

基于编程语言的  linter 模式，还能做很多的事情。 比如，自动 fix 功能。

能否添加类似以下的命令：

* `FixChinese` : 自动 fix 所有的错误
* `FixChineseLine`: 自动 fix 当前行的错误

**Comment by Freed-Wu** [comment]
确实如此。但`pangu.vim` 可以自动fix错误。不过它的fix不能使用范围，也就是全文都fix，有时只想fix自己写的某一部分就很不方便了。不过现在有`ale`和`neoformat`这样的linter和formater，不知道可不可以对中文错误进行检查和修正

**Comment by FuDesign2008** [comment]
> 确实如此。但`pangu.vim` 可以自动fix错误。不过它的fix不能使用范围，也就是全文都fix，有时只想fix自己写的某一部分就很不方便了。不过现在有`ale`和`neoformat`这样的linter和formater，不知道可不可以对中文错误进行检查和修正

目前主要使用 vim +  markdown，配置 [vim-markdown](https://github.com/plasticboy/vim-markdown)  和 [prettier](https://prettier.io/) 可以搞定对 markdown 格式的大部分要求（比如 `英文和数字之间没有空格` 这种，但应该没有对中文标点符号/汉字进行优化），结合 ALE  进行自动format

**Comment by wsdjeg** [comment]
没有想到比较好的实现方式，这个语法检擦是基于正则匹配的。
